apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: damage-predictor-deployment
      labels:
        app: damage-predictor
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: damage-predictor
      template:
        metadata:
          labels:
            app: damage-predictor
        spec:
          containers:
            - name: damage-predictor
              image: crunchyblue/damage-predictor:latest
              ports:
                - containerPort: 5000
          imagePullSecrets:
            - name: registry-key

  - apiVersion: v1
    kind: Service
    metadata:
      name: predictor-service
    spec:
      type: NodePort
      selector:
        app: damage-predictor
      ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
          nodePort: 30002